// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmvafvyawpngrcmqnsmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtdmFmdnlhd3BuZ3JjbXFuc21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4MzE0NzgsImV4cCI6MjA4NDQwNzQ3OH0.mUhNKCxCse4sbRDPmj_ATOnrDGZTmwVXGI_cNgS5suo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});